channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=24.3.1
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - numpy==2.1.3
  - pandas==2.3.0
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.15.3
name: mlflow-env