name: health-and-sleep-relation-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/final_dataset.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Check Env
        run: |
          echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(mlflow search-runs --max-results 1 --output json | jq -r '.[0].run_id')
          echo "Latest run_id: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT