name: MLflow CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Start MLflow CI/CD Pipeline"

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: mlflow-env
        environment-file: conda.yaml
        python-version: 3.12.7

    - name: Install MLflow (outside env)
      run: pip install mlflow

    - name: Run MLflow project with conda
      run: |
        mlflow run .  # Akan otomatis gunakan conda.yaml

    - name: Get latest MLflow run_id
      id: get-run-id
      run: |
        run_id=$(mlflow experiments list | awk 'NR==2{print $1}')
        echo "Run ID: $run_id"
        echo "run_id=$run_id" >> $GITHUB_ENV

    - name: Print run_id
      run: echo "Latest Run ID is ${{ env.run_id }}"