name: ML Project CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
  GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Check Env
        run: |
          echo "GDRIVE_CREDENTIALS length: ${#GDRIVE_CREDENTIALS}"
          echo "GDRIVE_FOLDER_ID: $GDRIVE_FOLDER_ID"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(find mlruns/0/models -type f -name "meta.yaml" | sort | tail -n1 | xargs dirname | xargs basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest MLflow run_id: $RUN_ID"
          ls -l mlruns/0/models/$RUN_ID/artifacts
          cat mlruns/0/models/$RUN_ID/artifacts/MLmodel

      - name: Install Python dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        run: python MLproject/upload_to_gdrive.py

      - name: Build Docker Model
        run: mlflow models build-docker -m mlruns/0/models/$RUN_ID/artifacts --name "health-and-sleep-relation"
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Tag Docker Image
        run: docker tag health-and-sleep-relation ${{ secrets.DOCKERHUB_USERNAME }}/health-and-sleep-relation:latest
  
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/health-and-sleep-relation:latest
