name: health-and-sleep-relation-CI

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/final_dataset.csv" 
  CONDA_ENV_NAME: "mlflow-ci-env"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Set up Miniconda and Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.12.7" 
          channels: conda-forge
          miniforge-version: latest
          activate-environment: ${{ env.CONDA_ENV_NAME }}

      - name: Create Conda environment
        run: |
          conda create -n ${{ env.CONDA_ENV_NAME }} python=3.12.7 -y

      - name: Check Env
        run: |
          echo "CSV_URL: ${{ env.CSV_URL }}"
          echo "Current Python path: $(which python)" # Memastikan Python dari Conda yang benar digunakan
          echo "Current PATH: $PATH" # Memeriksa PATH
          conda env list # List conda environments untuk konfirmasi pembuatan dan aktivasi

      - name: Install dependencies
        run: |
          pip install mlflow
          conda env update -n ${{ env.CONDA_ENV_NAME }} -f MLproject/conda.yaml

      - name: Run mlflow project
        run: |
          python -m mlflow run MLproject/ --no-conda

      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin main
