name: ML Project CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
  GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Check Env
        run: |
          echo "GDRIVE_CREDENTIALS length: ${#GDRIVE_CREDENTIALS}"
          echo "GDRIVE_FOLDER_ID: $GDRIVE_FOLDER_ID"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          echo "RUN_ID=$(ls -t mlruns/0 | head -n1)" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        run: python MLproject/upload_to_gdrive.py

      - name: Build Docker Model
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:v1

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:v1
